import type { NextPage } from "next"
import Link from 'next/link'
import Head from "next/head"
import { useSession } from "next-auth/react"
import { inferProcedureOutput } from "@trpc/server"
import { trpc } from "../utils/trpc"
import { AppRouter } from '../server/trpc/router/_app'
import { Apps } from "../components/pages/home"
import { Nav, Loading } from '../components/commons'

type AppsData = inferProcedureOutput<AppRouter['apps']['all']>

const Home: NextPage = () => {
  const { isLoading, data, refetch } = trpc.apps.all.useQuery() 
  const { data: session, status } = useSession()

	const handleRefetch = async () => {
    await refetch()
	}
  
  return (
    <>
      <Head>
        <title>List of applications</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav />
      </header>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
				{ isLoading ? <Loading /> : (
					<>
						<h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
							List of <span className="text-purple-300">Lattice</span> Apps
						</h1>
						<div className="flex w-full max-w-4xl flex-row-reverse mb-3 mt-7">
              {
                session && (
                  <Link href="/add">
                    <button>
                      <div className="px-4 py-2 border-2 border-black flex items-center justify-center rounded font-bold text-gray-700 text-lg hover:bg-gray-700 hover:text-white">
                        <div className="text-xl font-bold mr-3">Create a new app</div>
                        <h2 className="text-lg">+</h2>
                      </div>
                    </button>
                  </Link>
                )     
              }
						</div>
						<div className="flex flex-col w-full mx-auto justify-center items-center">
							{ data && <Apps apps={data} session={session} refetch={handleRefetch} /> }
						</div>
					</>
				)}
      </main>
    </>
  )
}



export default Home
